/**
 * Bundled audio manifest — keyed by corpus name ID.
 *
 * PLACEHOLDER: All entries point to the same silent placeholder clip.
 * Before release: replace each value with the correct per-name asset
 * (e.g. require('../assets/audio/allah.mp3')) and confirm rights to bundle.
 * The audio service (player.ts) reads this map and stays unchanged.
 * SPEC §5, AGENTS.md §Audio.
 */

// eslint-disable-next-line @typescript-eslint/no-var-requires
const PLACEHOLDER = require('../assets/audio/placeholder.wav') as number;

const manifest: Record<string, number> = {
  allah: PLACEHOLDER,
  ar_rahman: PLACEHOLDER,
  ar_rahim: PLACEHOLDER,
  al_malik: PLACEHOLDER,
  al_quddus: PLACEHOLDER,
  as_salam: PLACEHOLDER,
  al_mumin: PLACEHOLDER,
  al_muhaymin: PLACEHOLDER,
  al_aziz: PLACEHOLDER,
  al_jabbar: PLACEHOLDER,
  al_mutakabbir: PLACEHOLDER,
  al_khaliq: PLACEHOLDER,
  al_bari: PLACEHOLDER,
  al_musawwir: PLACEHOLDER,
  al_ghaffar: PLACEHOLDER,
  al_qahhar: PLACEHOLDER,
  al_wahhab: PLACEHOLDER,
  ar_razzaq: PLACEHOLDER,
  al_fattah: PLACEHOLDER,
  al_alim: PLACEHOLDER,
  al_qabid: PLACEHOLDER,
  al_basit: PLACEHOLDER,
  al_khafid: PLACEHOLDER,
  ar_rafi: PLACEHOLDER,
  al_muizz: PLACEHOLDER,
  al_mudhill: PLACEHOLDER,
  as_sami: PLACEHOLDER,
  al_basir: PLACEHOLDER,
  al_hakam: PLACEHOLDER,
  al_adl: PLACEHOLDER,
  al_latif: PLACEHOLDER,
  al_khabir: PLACEHOLDER,
  al_halim: PLACEHOLDER,
  al_azim: PLACEHOLDER,
  al_ghafur: PLACEHOLDER,
  ash_shakur: PLACEHOLDER,
  al_ali: PLACEHOLDER,
  al_kabir: PLACEHOLDER,
  al_hafiz: PLACEHOLDER,
  al_muqit: PLACEHOLDER,
  al_hasib: PLACEHOLDER,
  al_jalil: PLACEHOLDER,
  al_karim: PLACEHOLDER,
  ar_raqib: PLACEHOLDER,
  al_mujib: PLACEHOLDER,
  al_wasi: PLACEHOLDER,
  al_hakim: PLACEHOLDER,
  al_wadud: PLACEHOLDER,
  al_majid: PLACEHOLDER,
  al_baith: PLACEHOLDER,
  ash_shahid: PLACEHOLDER,
  al_haqq: PLACEHOLDER,
  al_wakil: PLACEHOLDER,
  al_qawi: PLACEHOLDER,
  al_matin: PLACEHOLDER,
  al_wali: PLACEHOLDER,
  al_hamid: PLACEHOLDER,
  al_muhsi: PLACEHOLDER,
  al_mubdi: PLACEHOLDER,
  al_muid: PLACEHOLDER,
  al_muhyi: PLACEHOLDER,
  al_mumit: PLACEHOLDER,
  al_hayy: PLACEHOLDER,
  al_qayyum: PLACEHOLDER,
  al_wajid: PLACEHOLDER,
  al_majd: PLACEHOLDER,
  al_wahid: PLACEHOLDER,
  as_samad: PLACEHOLDER,
  al_qadir: PLACEHOLDER,
  al_muqtadir: PLACEHOLDER,
  al_muqaddim: PLACEHOLDER,
  al_muakhkhir: PLACEHOLDER,
  al_awwal: PLACEHOLDER,
  al_akhir: PLACEHOLDER,
  az_zahir: PLACEHOLDER,
  al_batin: PLACEHOLDER,
  al_wali_gov: PLACEHOLDER,
  al_mutaali: PLACEHOLDER,
  al_barr: PLACEHOLDER,
  at_tawwab: PLACEHOLDER,
  al_muntaqim: PLACEHOLDER,
  al_afuw: PLACEHOLDER,
  ar_rauf: PLACEHOLDER,
  malik_al_mulk: PLACEHOLDER,
  dhul_jalal: PLACEHOLDER,
  al_muqsit: PLACEHOLDER,
  al_jami: PLACEHOLDER,
  al_ghani: PLACEHOLDER,
  al_mughni: PLACEHOLDER,
  al_mani: PLACEHOLDER,
  ad_darr: PLACEHOLDER,
  an_nafi: PLACEHOLDER,
  an_nur: PLACEHOLDER,
  al_hadi: PLACEHOLDER,
  al_badi: PLACEHOLDER,
  al_baqi: PLACEHOLDER,
  al_warith: PLACEHOLDER,
  ar_rashid: PLACEHOLDER,
  as_sabur: PLACEHOLDER,
  // Further Names corpus entries
  al_ahad: PLACEHOLDER,
  al_qarib: PLACEHOLDER,
  ar_rabb: PLACEHOLDER,
  al_fatir: PLACEHOLDER,
};

export default manifest;
